=== JesusFerreras/2324_lmsgi/ud4/10/10.dtd
<!ELEMENT pagina (receta+)>
    <!ELEMENT receta (nombre, descripcion?, tiempo, ingredientes, instrucciones?)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT tiempo EMPTY>
            <!ATTLIST tiempo preparacion CDATA #IMPLIED>
            <!ATTLIST tiempo coccion CDATA #REQUIRED>
        <!ELEMENT ingredientes (ingrediente+)>
            <!ELEMENT ingrediente (nombreI, cantidad?)>
                <!ELEMENT nombreI (#PCDATA)>
                <!ELEMENT cantidad (#PCDATA)>
                    <!ATTLIST cantidad unidad (gramos|pizca|mililitros|cucharada|chorro) #IMPLIED>
        <!ELEMENT instrucciones (paso+)>
            <!ELEMENT paso (#PCDATA)>
        <!ATTLIST receta plato (primero|segundo|postre) "primero">
    <!ATTLIST pagina xmlns:xsi CDATA #IMPLIED>
    <!ATTLIST pagina xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

=== JesusFerreras/2324_lmsgi/ud4/10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pagina SYSTEM "10.dtd">
<pagina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="10.xsd">
    <receta plato="primero">
        <nombre>Risotto milanesa</nombre>
        <tiempo coccion="20"/>
        <ingredientes>
            <ingrediente>
                <nombreI>arroz</nombreI>
                <cantidad unidad="gramos">500</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>cebolla</nombreI>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>azafrán</nombreI>
                <cantidad unidad="pizca">1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>queso parmesano</nombreI>
                <cantidad unidad="gramos">100</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>mantiquilla</nombreI>
                <cantidad unidad="gramos">100</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>sal</nombreI>
            </ingrediente>
            <ingrediente>
                <nombreI>pimienta</nombreI>
            </ingrediente>
            <ingrediente>
                <nombreI>caldo</nombreI>
                <cantidad unidad="mililitros">1000</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreI>vino blanco</nombreI>
                <cantidad unidad="chorro">1</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>
            <paso>Picamos la cebolla y la pochamos con la mitad de la mantequilla.</paso>
            <paso>Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca.</paso>
            <paso>A continuación, incorporamos el arroz, lo sofreímos un poco.</paso>
            <paso>Vamos añadiendo el caldo caliente poco a poco mientras removemos.</paso>
            <paso>Salpimentamos.</paso>
            <paso>Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso.</paso>
            <paso>Servimos enseguida.</paso>
        </instrucciones>
    </receta>
</pagina>
