=== JesusFerreras/2324_lmsgi/ud4/04/04.dtd
<!ELEMENT curriculum (nombre,apellido+,anyo_nac,residencia,datos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT anyo_nac (#PCDATA)>
    <!ELEMENT residencia (ciudad,pais)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
    <!ELEMENT datos (tlfn?,correo?,perfil?,descr?,competencia*,formacion+,experiencia*)>
        <!ELEMENT tlfn (#PCDATA)>
        <!ELEMENT correo (#PCDATA)>
        <!ELEMENT perfil (#PCDATA)>
        <!ELEMENT descr (#PCDATA)>
        <!ELEMENT competencia (nom_com,nivel)>
            <!ELEMENT nom_com (#PCDATA)>
            <!ELEMENT nivel (#PCDATA)>
        <!ELEMENT formacion (titulo,centro,anyo_tit)>
            <!ELEMENT titulo (#PCDATA)>
            <!ELEMENT centro (#PCDATA)>
            <!ELEMENT anyo_tit (#PCDATA)>
        <!ELEMENT experiencia (puesto,empresa,anyo_ini,anyo_fin?)>
            <!ELEMENT puesto (#PCDATA)>
            <!ELEMENT empresa (#PCDATA)>
            <!ELEMENT anyo_ini (#PCDATA)>
            <!ELEMENT anyo_fin (#PCDATA)>

=== JesusFerreras/2324_lmsgi/ud4/04/04.xml
<?xml version="1.0" encodint="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "04.dtd">
<curriculum>
    <nombre></nombre>
    <apellido></apellido>
    <anyo_nac></anyo_nac>
    <residencia>
        <ciudad></ciudad>
        <pais></pais>
    </residencia>
    <datos>
        <tlfn></tlfn>
        <correo></correo>
        <perfil></perfil>
        <descr></descr>
        <competencia>
            <nom_com></nom_com>
            <nivel></nivel>
        </competencia>
        <formacion>
            <titulo></titulo>
            <centro></centro>
            <anyo_tit></anyo_tit>
        </formacion>
        <experiencia>
            <puesto></puesto>
            <empresa></empresa>
            <anyo_ini></anyo_ini>
            <anyo_fin></anyo_fin>
        </experiencia>
    </datos>
</curriculum>
