=== JesusFerreras/2324_lmsgi/EX03/03.dtd
<!ELEMENT manual (servicio,descripcion?,version,fecha_actualizacion?,requisitos_del_sistema,otros_datos,pasos_de_instalacion)>
    <!ELEMENT servicio (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT version (#PCDATA)>
    <!ELEMENT fecha_actualizacion (#PCDATA)>
    <!ELEMENT requisitos_del_sistema (sistema_operativo,memoria_ram,espacio_en_disco,puertos_disponibles)>
        <!ELEMENT sistema_operativo (#PCDATA)>
        <!ELEMENT memoria_ram (#PCDATA)>
            <!ATTLIST memoria_ram medida (Gb) #REQUIRED>
        <!ELEMENT espacio_en_disco (#PCDATA)>
            <!ATTLIST espacio_en_disco medida (Gb|Mb|Tb|Pb) "Gb">
        <!ELEMENT puertos_disponibles (puerto+)>
            <!ELEMENT puerto (#PCDATA)>
    <!ELEMENT otros_datos (url*)>
        <!ELEMENT url (#PCDATA)>
            <!ATTLIST url pagina (oficial|wiki|doc|repositorio) "oficial">
    <!ELEMENT pasos_de_instalacion (paso+)>
        <!ELEMENT paso (comando,descripcionP)>
            <!ELEMENT comando (#PCDATA)>
            <!ELEMENT descripcionP (#PCDATA)>
    <!ATTLIST manual codigo CDATA #REQUIRED>
    <!ATTLIST manual xmlns:xsi CDATA #IMPLIED>
    <!ATTLIST manual xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

=== JesusFerreras/2324_lmsgi/EX03/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manual SYSTEM "03.dtd">
<manual codigo="MAN01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <servicio>Servidor Apache</servicio>
    <descripcion>El servidor HTTP Apache de c√≥digo abierto, para plataformas Unix, Microsoft Windows, Macintosh y otras, implementa HTTP/1.1 y sitios virtuales</descripcion>
    <version>2.4</version>
    <fecha_actualizacion>2024-02-12</fecha_actualizacion>
    <requisitos_del_sistema>
        <sistema_operativo>Linux</sistema_operativo>
        <memoria_ram medida="Gb">2</memoria_ram>
        <espacio_en_disco medida="Gb">100</espacio_en_disco>
        <puertos_disponibles>
            <puerto>80</puerto>
            <puerto>443</puerto>
        </puertos_disponibles>
    </requisitos_del_sistema>
    <otros_datos>
        <url pagina="oficial">https://httpd.apache.org/</url>
        <url pagina="wiki">https://es.wikipedia.org/wiki/Servidor_HTTP_Apache</url>
    </otros_datos>
    <pasos_de_instalacion>
        <paso>
            <comando>sudo apt install apache2</comando>
            <descripcionP>Descargar e instalar el paquete apache2</descripcionP>
        </paso>
        <paso>
            <comando>sudo service apache2 status</comando>
            <descripcionP>Comprobar el estado del servicio</descripcionP>
        </paso>
        <paso>
            <comando>sudo ufw allow Apache</comando>
            <descripcionP>Abrir el cortafuegos el puerto 80 y 443</descripcionP>
        </paso>
    </pasos_de_instalacion>
</manual>
